# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.roastDegreeLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.roastDegreeLineEdit.setObjectName("roastDegreeLineEdit")
        self.verticalLayout.addWidget(self.roastDegreeLineEdit)
        self.priceLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.verticalLayout.addWidget(self.priceLineEdit)
        self.saveButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Add/Edit Coffee"))
        self.nameLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Name"))
        self.roastDegreeLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Roast Degree"))
        self.priceLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Price"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Save"))
