# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoffeeApp(object):
    def setupUi(self, CoffeeApp):
        CoffeeApp.setObjectName("CoffeeApp")
        CoffeeApp.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(CoffeeApp)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadDataButton.setObjectName("loadDataButton")
        self.verticalLayout.addWidget(self.loadDataButton)
        self.addCoffeeButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCoffeeButton.setObjectName("addCoffeeButton")
        self.verticalLayout.addWidget(self.addCoffeeButton)
        self.editCoffeeButton = QtWidgets.QPushButton(self.centralwidget)
        self.editCoffeeButton.setObjectName("editCoffeeButton")
        self.verticalLayout.addWidget(self.editCoffeeButton)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout.addWidget(self.tableWidget)
        CoffeeApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(CoffeeApp)

    def retranslateUi(self, CoffeeApp):
        _translate = QtCore.QCoreApplication.translate
        CoffeeApp.setWindowTitle(_translate("CoffeeApp", "Coffee App"))
        self.loadDataButton.setText(_translate("CoffeeApp", "Загрузить данные о кофе"))
        self.addCoffeeButton.setText(_translate("CoffeeApp", "Add Coffee"))
        self.editCoffeeButton.setText(_translate("CoffeeApp", "Edit Coffee"))
